[package]
name = "vulcan-chain-parser"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
vulcan-core.workspace = true
kdl.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true
