[package]
name = "vulcan-api"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
vulcan-core = { workspace = true, features = ["migrations"] }
dotenvy.workspace = true
